# Create a AWS EC2 VPC for a general purpose server.
#
# This uses Amazon Web Services (AWS) Elastic Compute Cloud (EC2).
#
# This uses environment variables:
#
#    * AWS_ACCESS_KEY or EC2_ACCESS_KEY
#    * AWS_SECRET_ACCESS_KEY or EC2_SECRET_KEY
#
# VPC means a virtual private cloud (VPC): a virtual network
# dedicated to your AWS account. It is logically isolated from
# other virtual networks in the AWS cloud. You can launch your AWS
# resources, such as Amazon EC2 instances, into your VPC. You can
# configure your VPC; you can select its IP address range, create
# subnets, and configure route tables, network gateways, and
# security settings.
#
# To see if your account has VPC available, start here:
# https://console.aws.amazon.com/ec2/v2/home
#
#   * Look for the section called "Account Attributes".
#   * Look for "Supported Platforms", then "EC2" and/or "VPC".
#
- name: AWS EC2 VPC for general purpose server
  ec2_vpc:
    state: present

    # AWS EC2 Region: Currently we prefer US East (N. Virgina) because
    # it's the only one that's able to use Cluster Compute instances,
    # and also it's the region where we have our existing servers.
    #
    region: "{{ region | default('us-east-1') }}"

    # Specify a CIDR block for the VPC.
    #
    # Classless Inter-Domain Routing (CIDR) is a method for allocating
    # IP addresses and routing packets. CIDR notation is a compact
    # representation of an IP address and associated routing prefix.
    #
    # https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing
    #
    # Amazon recommends you specify a CIDR block from the private
    # (non-publicly routable) IP address ranges as specified in RFC
    # 1918; for example, 10.0.0.0/16, or 192.168.0.0/16.
    #
    # You can specify a range of publicly routable IP addresses;
    # however, Amazon currently does not support direct access to the
    # Internet from publicly routable CIDR blocks in a VPC.
    #
    cidr_block: "{{ cidr_block | default('10.0.0.0/16') }}"

    # Tags in this list are used in conjunction with the VPC CIDR
    # block to uniquely identify a VPC. This is in lieu of vpc_id.
    #
    # If a CIDR+Tag combination does not exist, create a new VPC.
    # VPC tags not on this list will be ignored.
    #
    resource_tags:
      zid: "{{ zid | default('general') }}"
