- name: "nvm installer via curl"
  shell: >
    curl -sSL -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash -
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
