- name: "nvm install via curl"
  become: yes
  become_user: root
  shell: "/usr/bin/curl -sSL -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash -"
  args:
    warn: false
